### ISSUE TITLE
Shoulda-context does not seem to work with Ruby 2.2

### ISSUE THREAD

**Issue by walro** [twingly/twingly-url#26]
I tried to change so that we test against 2.2. First I ran into to the following problem:

```ruby
/Users/robin/.gem/ruby/2.2.1/gems/shoulda-context-1.2.1/lib/shoulda/context/test_framework_detection.rb:9:in `block in possible_test_frameworks': cannot load such file -- test/unit (LoadError)
```

After adding `test-unit` as a development dependency: `s.add_development_dependency "test-unit", "~> 3"`:

```ruby
Error: test_: .extract_urls should detect two urls in an Array. (NormalizerTest)
: NameError: uninitialized class variable @@current in MiniTest::Unit::TestCase
/Users/robin/.gem/ruby/2.2.1/gems/minitest-4.7.5/lib/minitest/unit.rb:1297:in `current'
(eval):8:in `must_equal'
/Users/robin/Workspace/git/twingly-url/test/unit/normalization_test.rb:64:in `block (2 levels) in <class:NormalizerTest>'
/Users/robin/.gem/ruby/2.2.1/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `instance_exec'
/Users/robin/.gem/ruby/2.2.1/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:413:in `block in create_test_from_should_hash'
```

Looking at https://github.com/thoughtbot/shoulda-context they only test against 2.0.0 so I think we might want to remove this dependency.

**Comment by walro** [comment]
Fixed in #29
