### ISSUE TITLE
domain, sld, trd (maybe others) can be nil

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-url#52]
This breaks our applications.

```ruby
[8] pry(main)> Twingly::URL.parse("https://.com/").domain
=> nil
[9] pry(main)> Twingly::URL.parse("https://.com/").sld
=> nil
[10] pry(main)> Twingly::URL.parse("https://.com/").trd
=> nil
```

**Comment by walro** [comment]
```ruby
[5] pry(main)> uri = Addressable::URI.heuristic_parse("https://.com/AVisualStudios")
=> #<Addressable::URI:0x3ffeb1525144 URI:https://.com/AVisualStudios>
[6] pry(main)> uri.display_uri.host
=> ".com"
[7] pry(main)> PublicSuffix.parse(".com")
=> #<PublicSuffix::Domain:0x007ffd6329a1e0 @sld=nil, @tld="com", @trd=nil>
```

**Comment by dentarg** [comment]
```ruby
[13] pry(main)> url = Twingly::URL.parse("https://.com/")
=> #<Twingly::URL:0x3fe1dcd5b828 https://.com/>
[14] pry(main)> cd url
[15] pry(#<Twingly::URL>):1> ls
Comparable#methods: <  <=  ==  >  >=  between?
Twingly::URL#methods: <=>  domain  host  inspect  normalized  normalized_host  normalized_path  normalized_scheme  origin  path  scheme  sld  tld  to_s  trd  valid?  without_scheme
self.methods: __pry__
instance variables: @addressable_uri  @public_suffix_domain
locals: _  __  _dir_  _ex_  _file_  _in_  _out_  _pry_
[16] pry(#<Twingly::URL>):1> @public_suffix_domain
=> #<PublicSuffix::Domain:0x007fc3b9ab7190 @sld=nil, @tld="com", @trd=nil>
[17] pry(#<Twingly::URL>):1> @public_suffix_domain.domain
=> nil
```

Strange :)

**Comment by dentarg** [comment]
```ruby
[19] pry(#<Twingly::URL>):1> @public_suffix_domain.valid?
=> false
[20] pry(#<Twingly::URL>):1> @public_suffix_domain.valid_domain?
=> false
```

**Comment by dentarg** [comment]
Still think this case should count as a valid URL.

```sh
$ curl -s -v -o /dev/null `dig +short to`
* Rebuilt URL to: 216.74.32.107/
*   Trying 216.74.32.107...
* Connected to 216.74.32.107 (216.74.32.107) port 80 (#0)
> GET / HTTP/1.1
> Host: 216.74.32.107
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Mon, 26 Oct 2015 16:33:40 GMT
< Server: Apache/2.2.22
< Last-Modified: Thu, 07 Nov 2013 06:30:52 GMT
< ETag: "6e01ed-b1-4ea90683f1f00"
< Accept-Ranges: bytes
< Content-Length: 177
< Vary: Accept-Encoding
< Content-Type: text/html
<
{ [177 bytes data]
* Connection #0 to host 216.74.32.107 left intact
```

**Comment by dentarg** [comment]
.to is not the only one: http://blog.towo.eu/a-records-on-top-level-domains/

**Comment by dentarg** [comment]
```ruby
[4] pry(main)> Faraday.get "http://.to"
Faraday::ConnectionFailed: getaddrinfo: nodename nor servname provided, or not known
from /Users/dentarg/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
[5] pry(main)> Faraday.get "http://to"
Faraday::ConnectionFailed: getaddrinfo: nodename nor servname provided, or not known
from /Users/dentarg/.rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
```

:-(

**Comment by dentarg** [comment]
More variants to consider.

"http://xxx@.com/"
"http://...com"
"http://.ly/xxx"
"http://.com.my/"
"http://.net"
"http://.com."
"http://.gl/xxx"

**Comment by dentarg** [comment]
I'm okay with these being invalid URLs, just want us to solve this and not have the `nil`s :)

**Comment by roback** [comment]
The best solution I can come up with is adding the following to `Twingly::URL.internal_parse`:

```
raise Twingly::URL::Error::ParseError if addressable_uri.host.start_with?(".") || addressable_uri.host.end_with?(".")
```

Works with all urls in this issue, but `http://.twingly.com` (see #70) becomes a `NullURL` then too.

**Comment by roback** [comment]
Another way is adding `.to_s` in `#domain`, `#trd` etc., but then all URLs above would be considered valid :(

**Comment by walro** [comment]
Maybe #74 will fix some (all) of these?

**Comment by roback** [comment]
> Maybe #74 will fix some (all) of these?

Looks like it (disclaimer: I have not read the whole RFC :))

**Comment by roback** [comment]
Rubys `URI.parse` handles the above urls, so maby they're valid according to the rfc? In that case #74 doesn't fix any of these.

**Comment by walro** [comment]
Ah, I see. Too bad.

**Comment by roback** [comment]
Another solution is that the URL must always have a second level domain, which makes all above urls invalid.

```ruby
raise Twingly::URL::Error::ParseError unless public_suffix_domain.sld
```
