### ISSUE TITLE
JRuby compatibility (drop libidn requirement)

### ISSUE THREAD

**Issue by walro** [twingly/twingly-url#66]
Since the introduction of the `idn-ruby` gem in #63 we can no longer run under the Java runtime. Some ideas from the top of my head:
- Stop using the gem
- Is it possibly to have conditionals in the Gemfile? As in, don't use `idn-ruby` for Java platform.
- If above is possible it would mean that we'd handle urls different depending upon runtime which is not that desirable.

**Comment by jage** [comment]
> Is it possibly to have conditionals in the Gemfile? As in, don't use ìdn-ruby` for Java platform.

It is possible (See platform in http://bundler.io/man/gemfile.5.html)

> If above is possible it would mean that we'd handle urls different depending upon runtime which is not that desirable.

Agree, we'd like the same behaviour under JRuby and Ruby.

**Comment by dentarg** [comment]
> Since the introduction of the idn-ruby gem in #63 we can no longer run under the Java runtime.

#63 fixed #48 which was about https://github.com/sporkmonger/addressable/issues/215, which now has been fixed in https://github.com/sporkmonger/addressable/commit/cf8cc7d0b9c8d2df9caeff90a063864c3e68d940 and released in [Addressable 2.4.0](https://github.com/sporkmonger/addressable/compare/addressable-2.3.8...addressable-2.4.0).

**Comment by dentarg** [comment]
> Is it possibly to have conditionals in the Gemfile? As in, don't use idn-ruby for Java platform.

Yes: https://github.com/sporkmonger/addressable/blob/addressable-2.4.0/Gemfile#L27

**Comment by dentarg** [comment]
Tried Adressable 2.4.0 without `idn-ruby`

```diff
$ git d
diff --git a/lib/twingly/url.rb b/lib/twingly/url.rb
index 282e13a..499579e 100644
--- a/lib/twingly/url.rb
+++ b/lib/twingly/url.rb
@@ -1,5 +1,4 @@
 require "addressable/uri"
-require "addressable/idna/native"
 require "public_suffix"

 require_relative "url/null_url"
@@ -16,7 +15,7 @@ module Twingly
     ERRORS = [
       Addressable::URI::InvalidURIError,
       PublicSuffix::DomainInvalid,
-      IDN::Idna::IdnaError,
+      Addressable::IDNA::PunycodeBadInput,
     ]

     def self.parse(potential_url)
diff --git a/twingly-url.gemspec b/twingly-url.gemspec
index 915e5d2..b8be843 100644
--- a/twingly-url.gemspec
+++ b/twingly-url.gemspec
@@ -12,9 +12,8 @@ Gem::Specification.new do |s|
   s.license     = "MIT"
   s.required_ruby_version = "~> 2.2"

-  s.add_dependency "addressable", "~> 2"
+  s.add_dependency "addressable", "~> 2.4"
   s.add_dependency "public_suffix", "~> 1.4"
-  s.add_dependency "idn-ruby", "~> 0.1"

   s.add_development_dependency "rake", "~> 10"
   s.add_development_dependency "rspec", "~> 3"
```

Two failures (about the same URL)

```
Failures:

  1) Twingly::URL.parse when given valid urls does not ruin the url "http://xn--zckp1cyg1.sblo.jp/"
     Failure/Error: expect(described_class.parse(valid_url).to_s).to eq(valid_url)

       expected: "http://xn--zckp1cyg1.sblo.jp/"
            got: ""

       (compared using ==)
     # ./spec/lib/twingly/url_spec.rb:59:in `block (5 levels) in <top (required)>'

  2) Twingly::URL#valid? returns true for the valid url "http://xn--zckp1cyg1.sblo.jp/"
     Failure/Error: expect(described_class.parse(valid_url).valid?).to be true

       expected true
            got false
     # ./spec/lib/twingly/url_spec.rb:195:in `block (4 levels) in <top (required)>'
```

**Comment by dentarg** [comment]
```
# with idn-ruby
[6] pry(main)> Addressable::URI.parse("http://xn--zckp1cyg1.sblo.jp/").display_uri
=> #<Addressable::URI:0x3ff9cf027390 URI:http://xn--zckp1cyg1.sblo.jp/>

# without
[6] pry(main)> Addressable::URI.parse("http://xn--zckp1cyg1.sblo.jp/").display_uri
Addressable::IDNA::PunycodeBadInput: Input is invalid.
from /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.4.0/lib/addressable/idna/pure.rb:562:in `punycode_decode'
```

**Comment by walro** [comment]
Is http://xn--zckp1cyg1.sblo.jp/ valid? :)

**Comment by dentarg** [comment]
It's resolvable at least:

```
$ curl -v -L http://xn--zckp1cyg1.sblo.jp/
*   Trying 59.106.18.133...
* Connected to xn--zckp1cyg1.sblo.jp (59.106.18.133) port 80 (#0)
> GET / HTTP/1.1
> Host: xn--zckp1cyg1.sblo.jp
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Date: Mon, 07 Dec 2015 14:38:50 GMT
< Server: Apache
< Content-Length: 226
< Connection: close
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
* Closing connection 0
```

**Comment by walro** [comment]
Yes, but someone might have registered a "faulty" sub-domain. I tried some different online tools and they all had troubles converting it.

**Comment by walro** [comment]
But even so, we should of course not blow up.

**Comment by dentarg** [comment]
@walro I you want to you can weigh in at https://github.com/sporkmonger/addressable/issues/219

**Comment by dentarg** [comment]
@walro what tools did you try? sounds like we can change our spec then, if we revert the use of libidn

**Comment by walro** [comment]
> @walro what tools did you try? sounds like we can change our spec then, if we revert the use of libidn

https://www.punycoder.com/ and http://www.charset.org/punycode.php?encoded=xn--zckp1cyg1&decode=Punycode+to+normal+text

The latter does infact handle most part of it, but I suspect that the "box" at the end implicates an error.

However, I think our library should just treat it as a normal string that just happens to start with xn--, rather than blowing up so I don't see us reverting the use of libidn just yet.

**Comment by dentarg** [comment]
I played around with the CLI for libidn (from Homebrew)

```
$ idn --version
idn (GNU Libidn) 1.32
Copyright (C) 2015 Simon Josefsson.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Simon Josefsson.
```

```
$ idn --debug --idna-to-unicode xn--zckp1cyg1
Charset `UTF-8'.
input[0] = U+0078
input[1] = U+006e
input[2] = U+002d
input[3] = U+002d
input[4] = U+007a
input[5] = U+0063
input[6] = U+006b
input[7] = U+0070
input[8] = U+0031
input[9] = U+0063
input[10] = U+0079
input[11] = U+0067
input[12] = U+0031
output[0] = U+0078
output[1] = U+006e
output[2] = U+002d
output[3] = U+002d
output[4] = U+007a
output[5] = U+0063
output[6] = U+006b
output[7] = U+0070
output[8] = U+0031
output[9] = U+0063
output[10] = U+0079
output[11] = U+0067
output[12] = U+0031
xn--zckp1cyg1
```

Something valid:

```
$ idn --debug --idna-to-unicode xn--rksmrgs-5wao1o
Charset `UTF-8'.
input[0] = U+0078
input[1] = U+006e
input[2] = U+002d
input[3] = U+002d
input[4] = U+0072
input[5] = U+006b
input[6] = U+0073
input[7] = U+006d
input[8] = U+0072
input[9] = U+0067
input[10] = U+0073
input[11] = U+002d
input[12] = U+0035
input[13] = U+0077
input[14] = U+0061
input[15] = U+006f
input[16] = U+0031
input[17] = U+006f
output[0] = U+0072
output[1] = U+00e4
output[2] = U+006b
output[3] = U+0073
output[4] = U+006d
output[5] = U+00f6
output[6] = U+0072
output[7] = U+0067
output[8] = U+00e5
output[9] = U+0073
räksmörgås

**Comment by dentarg** [comment]
Played around some more

```
$ idn --punycode-decode xn--rksmrgs-5wao1o
xn--rksmrÂgÏÃs
```

```
$ idn --punycode-decode xn--zckp1cyg1
idn: punycode_decode: Invalid input
```

```
$ idn -h
Usage: idn [OPTION]... [STRINGS]...
Internationalized Domain Name (IDN) convert STRINGS, or standard input.

Command line interface to the internationalized domain name library.

All strings are expected to be encoded in the preferred charset used
by your locale.  Use `--debug' to find out what this charset is.  You
can override the charset used by setting environment variable CHARSET.

To process a string that starts with `-', for example `-foo', use `--'
to signal the end of parameters, as in `idn --quiet -a -- -foo'.

Mandatory arguments to long options are mandatory for short options too.
  -h, --help               Print help and exit
  -V, --version            Print version and exit
  -s, --stringprep         Prepare string according to nameprep profile
  -d, --punycode-decode    Decode Punycode
  -e, --punycode-encode    Encode Punycode
  -a, --idna-to-ascii      Convert to ACE according to IDNA (default mode)
  -u, --idna-to-unicode    Convert from ACE according to IDNA
      --allow-unassigned   Toggle IDNA AllowUnassigned flag (default off)
      --usestd3asciirules  Toggle IDNA UseSTD3ASCIIRules flag (default off)
      --no-tld             Don't check string for TLD specific rules
                             Only for --idna-to-ascii and --idna-to-unicode
  -n, --nfkc               Normalize string according to Unicode v3.2 NFKC
  -p, --profile=STRING     Use specified stringprep profile instead
                             Valid stringprep profiles: `Nameprep',
                             `iSCSI', `Nodeprep', `Resourceprep',
                             `trace', `SASLprep'
      --debug              Print debugging information
      --quiet              Silent operation

Report bugs to: bug-libidn@gnu.org
GNU Libidn home page: <http://www.gnu.org/software/libidn/>
General help using GNU software: <http://www.gnu.org/gethelp/>
```

**Comment by dentarg** [comment]
Ah `[21:47] Robin Wallin: prova punycode-decode utan xn--`

```
$ idn --punycode-decode zckp1cyg1
idn: punycode_decode: Invalid input

$ idn --punycode-decode rksmrgs-5wao1o
räksmörgås
```

**Comment by dentarg** [comment]
> sporkmonger/addressable#219

Has been solved (https://github.com/sporkmonger/addressable/commit/295d7baec1281976434e9061b8065979b3f38c83) but not yet released.

**Comment by dentarg** [comment]
>> sporkmonger/addressable#219
> Has been solved (sporkmonger/addressable@295d7ba) but not yet released.

Summary: with the fix in addressable we would be able to handle #48 without libidn

**Comment by dentarg** [comment]
> Summary: with the fix in addressable we would be able to handle #48 without libidn

with https://github.com/twingly/twingly-url/pull/90 we can drop the use of libidn, because we no longer need to use `#display_uri` in addressable (which has the bug that has been fixed but not yet released)

**Comment by dentarg** [comment]
Hmm, this is tricky... :| 

We have seen URLs like 

    http://AcinusFallumTrompetumNullunCreditumVisumEstAtCuadLongumEtCefallumEst.com

Without `libidn` it's valid:

```ruby
[1] pry(main)> Twingly::URL.parse("http://AcinusFallumTrompetumNullunCreditumVisumEstAtCuadLongumEtCefallumEst.com")
=> #<Twingly::URL:0x3fc872208c4c http://AcinusFallumTrompetumNullunCreditumVisumEstAtCuadLongumEtCefallumEst.com>
```


With `libidn` it's not valid:

```ruby
[1] pry(main)> Twingly::URL.parse("http://AcinusFallumTrompetumNullunCreditumVisumEstAtCuadLongumEtCefallumEst.com")
=> #<Twingly::URL::NullURL:0x007fe54b31c378>
```

this is the error

```ruby
[4] pry(main)> Addressable::URI.heuristic_parse("http://AcinusFallumTrompetumNullunCreditumVisumEstAtCuadLongumEtCefallumEst.com").normalized_host
IDN::Idna::IdnaError: Output would be too large or too small (5)
from /Users/dentarg/.gem/ruby/2.2.5/gems/addressable-2.4.0/lib/addressable/idna/native.rb:38:in `toASCII'
```

no `libidn` (using the pure Ruby version in addressable):

```
[1] pry(main)> Addressable::URI.heuristic_parse("http://AcinusFallumTrompetumNullunCreditumVisumEstAtCuadLongumEtCefallumEst.com").normalized_host
=> "acinusfallumtrompetumnulluncreditumvisumestatcuadlongumetcefallumest.com"
```

**Comment by walro** [comment]
I'd guess libidn conforms to the maxlength of 63, http://stackoverflow.com/questions/14402407/maximum-length-of-a-domain-name-without-the-http-www-com-parts

**Comment by dentarg** [comment]
I guess the consequence would be that we will see more `SocketError` happening:

```ruby
[3] pry(main)> Net::HTTP.get(URI("http://AcinusFallumTrompetumNullunCreditumVisumEstAtCuadLongumEtCefallumEst.com"))
SocketError: getaddrinfo: nodename nor servname provided, or not known
from /Users/dentarg/.rubies/ruby-2.2.5/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
```

**Comment by dentarg** [comment]
I reported the above mentioned difference in behaviour to addressable:  https://github.com/sporkmonger/addressable/issues/239

**Comment by dentarg** [comment]
> I reported the above mentioned difference in behaviour to addressable: sporkmonger/addressable#239

And it was fixed in https://github.com/sporkmonger/addressable/commit/c73810f4823c4dfac1f0568073623eb7922f526d
