### ISSUE TITLE
"ArgumentError: invalid byte sequence in US-ASCII" when parsing the public suffix list

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-url#98]
Seen in [an application](https://github.com/twingly/wally/issues/56) not using `LANG=en_US.UTF-8`:

```
ArgumentError: invalid byte sequence in US-ASCII
  from public_suffix/list.rb:89:in `strip!'
  from public_suffix/list.rb:89:in `block (2 levels) in parse'
  from public_suffix/list.rb:88:in `each_line'
  from public_suffix/list.rb:88:in `block in parse'
  from public_suffix/list.rb:128:in `initialize'
  from public_suffix/list.rb:87:in `new'
  from public_suffix/list.rb:87:in `parse'
  from twingly/public_suffix_list.rb:12:in `with_punycoded_names'
  from twingly/url.rb:15:in `<class:URL>'
  from twingly/url.rb:11:in `<module:Twingly>'
  from twingly/url.rb:10:in `<top (required)>'
  from twingly/url/hasher.rb:3:in `require_relative'
  from twingly/url/hasher.rb:3:in `<top (required)>'
  from /home/deploy/twingly-wally/releases/20160916113112/lib/models/...
```

Fortunately, we read the list ourselves, so we can read it with the correct encoding.

(public_suffix just trusts the default encoding: https://github.com/weppos/publicsuffix-ruby/blob/v2.0.2/lib/public_suffix/list.rb#L52)

**Comment by dentarg** [comment]
> (public_suffix just trusts the default encoding: https://github.com/weppos/publicsuffix-ruby/blob/v2.0.2/lib/public_suffix/list.rb#L52)

Since https://github.com/weppos/publicsuffix-ruby/issues/94

**Comment by dentarg** [comment]
> (public_suffix just trusts the default encoding: https://github.com/weppos/publicsuffix-ruby/blob/v2.0.2/lib/public_suffix/list.rb#L52)

Suggested to public_suffix that they always use UTF-8: https://github.com/weppos/publicsuffix-ruby/issues/118
